// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sllkasbcxbpcvdcjwjxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsbGthc2JjeGJwY3ZkY2p3anhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDE3NzcsImV4cCI6MjA3MDY3Nzc3N30.tPJU5cydp733BEKFI6r4vzlTDBkTEDpFLRpUgT8F3O0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});