// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcmnexqimyiiidnwowqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjbW5leHFpbXlpaWlkbndvd3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTIwOTUsImV4cCI6MjA3MzA4ODA5NX0.wcwBupOfNP5N6hhMpYdZaEmEdp2Q6YW5VKFYTnHO8CY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});